language: node_js
sudo: false
matrix:
    include:
      - os: linux
        node_js: '6'
      - os: linux
        node_js: '7'
      - os: linux
        node_js: '8'
      - os: linux
        node_js: '9'
      - os: osx
        node_js: '6'
      - os: osx
        node_js: '7'
      - os: osx
        node_js: '8'
      - os: osx
        node_js: '9'
install:
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run test
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"